### ISSUE TITLE
Frage: RealismAddon_rpmAnimSpeeds

### ISSUE THREAD

**Issue by Fracking** [s4t4n/FS22_CVT_Addon#10]
Hallo,
erstmal danke für den/die Mod.

In der Modbeschreibung steht, dass das Handgas, zusammen mit RealismAddon_rpmAnimSpeeds, die Hydraulik und PTO-Leistung optisch regelt. Ich kann RealismAddon_rpmAnimSpeeds aber nirgends (Google) finden. Ist das ein WIP oder Privates Projekt?

Vielen Dank im Voraus.

**Comment by s4t4n** [comment]
Der mod ist im Moment leider noch nicht offiziell.
Der Mod stammt ursprünglich von Sam, Modelleicher.
