### ISSUE TITLE
Q: slightly change behavior of overload transmission

### ISSUE THREAD

**Issue by DrewCZ** [s4t4n/FS22_CVT_Addon#12]
Hi, first, thank you for this amazing mod! Pushes the game closer to reality. 
My question, or please, is a little change of behavior when transmission is overloaded. Now appears message "gearbox overload, watch temp..." and a tractor is a little stuck. Ok. Is it possible to show a warning light on your CVT panel before this situation starts? Yellow for warning and red for damaging (without that message on the screen)? Because when I ride with a heavy load, I have to hold power under damage, but on max value. Hope it makes sense for you. It can be a little fine enhancement in the future. Thank you. 
Cheers, ticho aka DrewCZ

**Comment by s4t4n** [comment]
Hi,
with a heavy transport, you have to reduce the Acceleration-Ramp to 3 or 2.
Before the damage starts, the temperature will go up.

**Comment by DrewCZ** [comment]
Did you mean the temperature of the engine in-game? I think not. Because the engine was cold enough. And yes, I know how to handle heavy transport :-) 

Exactly, this is "a message **_about_** the damage".

And I'll be very happy when **_before_** this situation starts, I'll receive the **_warning_**. Something like a yellow light on your nice CVT display which can mean: warning! you are close to the damaged gearbox.  Maybe called a "high gearbox temperature warning lamp".

**Comment by Fracking** [comment]
Hi,
some sort of temperature senor feedback would be nice. I'd say "just" make the HUD color of the acceleration ramps change.
E.g. ramp 4 is too high for x-load and the temperature rises >safe temp: change the color from green to orange. -> for damage: change orange to red.
If the player lowers the ramp or the temperature drops down to normal levels, the color would go back to orange/green.

I don't know if it would work, but I guess it would be an easy way to give feedback to (inexperienced) players.
Just my thoughts...

Best regards.

**Comment by s4t4n** [comment]
yes I will do something like that.
But first I have to fix the new situation on server issue cuz of other issues poped out there, because other fixes
