### ISSUE TITLE
MP behavior and tuning

### ISSUE THREAD

**Issue by DrewCZ** [s4t4n/FS22_CVT_Addon#13]
Hi Sebastian, are you interested in MP behavior? Do you know if we can help with testing? Are there some debug messages for CVT? 

We are playing in MP and we have the following behavior tracked:
client: a message about damage disappears in a very short time
client: damage varies between 100%-0% slowly. In cca 1 minute goes to 0, then goes back to the actual value. 
server: can see clients' messages (not fully confirmed yet). 

One question: You did mean in the description mod, named 'RealismAddon_rpmAnimSpeeds'. Is this mod available for download somewhere? 
Thank you for your work on the mod!

**Comment by s4t4n** [comment]
Hey,
what do you mean exaclty with `server: can see clients' messages (not fully confirmed yet).` ?

RealismAddon_rpmAnimSpeeds is not public atm, it's a mod from modelleicher.
for the damage goes down, there will coming an update soon.

**Comment by DrewCZ** [comment]
When I was on the server side (not dedic, but my PC), I could see messages about overload. I checked my state of damage and nothing happened on my side. But on the client, my colleague saw a very short message (less than 1 sec.) and then his tractor was more damaged. it happens more than twice cca in 10 minutes. But we were not focused on testing this situation. 
I'm only writing because I've seen the messages, not about damaging processes themselves, etc.
