### ISSUE TITLE
Cannot change RPM anymore after latest update and rpm jumps weirdly at high speed

### ISSUE THREAD

**Issue by Tubezki** [s4t4n/FS22_CVT_Addon#14]
Hi,

After latest update I can't change RPM anymore and rpm jumps weirdly at high speed while driving which causes tractor sounds to act weirdly. Maybe add some smoothing or something? It used to be better before this update but now it jumps even more and causes tractors to sound a bit bad.

**Comment by Tubezki** [comment]
https://www.youtube.com/watch?v=n4-07GyeC2E

**Comment by DrewCZ** [comment]
thank you for YT, so please watch https://github.com/s4t4n/FS22_CVT_Addon#readme where is exactly this behavior described in part "Known issues". Hope the author of the gearbox will fix it soon. This is my opinion.
