### ISSUE TITLE
Czech translation xml file for you

### ISSUE THREAD

**Issue by DrewCZ** [s4t4n/FS22_CVT_Addon#16]
Hi, here is a little "thank you" for your work :) Czech translation XML file. Due to the XML format is not supported, please simply remove the file extension TXT. 
(I can't create pull, because I'm not a contributor)
[modDesc_l10n_cz.xml.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/12698298/modDesc_l10n_cz.xml.txt)

**Comment by s4t4n** [comment]
thank you ! =)
