### ISSUE TITLE
ActionEvent sync a nil value (Feh)

### ISSUE THREAD

**Issue by LohnunternehmenCP** [s4t4n/FS22_CVT_Addon#17]
C:/Users/Administrator/Documents/My Games/FarmingSimulator2022/mods/FS22_CVT_Addon/CVT_Addon.lua:2162: attempt to compare number with nil bitte um hilfe habe einen dedi server

**Comment by s4t4n** [comment]
mit oder ohne vca aktiv zu haben?

**Comment by LohnunternehmenCP** [comment]
Hab diese mods noch aktiv am server FS22_VehicleControlAddon-FS22_REAwheels-FS22_REAimplements-FS22_REAcog-FS22_REAgui-FS22_EnhancedVehicle-FS22_guidanceSteering danke für die schnelle Antwort

**Comment by s4t4n** [comment]
okay.. probier das bitte noch mal mit den beiden neuen Dateien, die ich eben hochgeladen habe...

CVT_Addon.lua
events/SyncClientServerEvent.lua

**Comment by LohnunternehmenCP** [comment]
cool danke ja werde ich machen aber dadurch das giants das problem hat das der server so spät auftaucht dauert das wieder gib sofort bescheid danke echt super :))

**Comment by s4t4n** [comment]
ja das Problem scheint immer noch zu bestehen, daß die Master-Listener Server von Giants nicht richtig laufen.
Das schränkt alle modder und scripter vor allem beim Testen ein. Wir müssten die Kisten ständig starten, stoppen ^^
Da fühlt man sich wie mit der unreal engine damals bei ut :D

**Comment by LohnunternehmenCP** [comment]
versteh ich voll warte noch immer bis er mir den neuen server anzeigt bis jetzt immer noch der alte

**Comment by s4t4n** [comment]
ich finde gar keinen atm
Im Forum bei Giants habe ich auch nichts entdeckt auf die Schnelle.. denke "wenn" wude es über den bugtracker gemeldet.
Aber da müssen die was machen, ggf. einen Backup-Server dafür bereitstellen, Falls einer Ausfällt^^. So machen das andere auch.

**Comment by LohnunternehmenCP** [comment]
Jetzt ging es erst wieder muss aber jetzt ins bett leider hab ich noch immer den fehler 
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/12778322/log.txt)
