### ISSUE TITLE
ConfigId wird nicht geladen (Aktiviert sich wieder selbst)

### ISSUE THREAD

**Issue by Swener33** [s4t4n/FS22_CVT_Addon#18]
aktiviert sich nach spiel neustart wieder bei jedem fahrzeug,wo man des deaktivert hat.

**Comment by s4t4n** [comment]
log?

**Comment by Swener33** [comment]
es ist mir aufgefallen da ich bei einigen die shop config auf nein gestellt habe, und  dann gespeichert habe als ich das game neu startete war alles wie zuvor CVT addon war wieder aktiv

**Comment by s4t4n** [comment]
Alles wie zuvor heißt.. alles auf "Klassisch" oder alle unterschiedlich je nach config?

**Comment by s4t4n** [comment]
schick mal bitte die log.txt.. hier oder im doscord

**Comment by Swener33** [comment]
Genau wie beim ersten start mit CVT addon alle fahrzeuge auf klassisch

**Comment by Swener33** [comment]
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/12840936/log.txt)

hier die log
