### ISSUE TITLE
Wie aktiviere ich das CVT addon

### ISSUE THREAD

**Issue by Ahirsch57** [s4t4n/FS22_CVT_Addon#20]
Ich versthe nicht ganz wie ich das CVT Addon aktiviere ich habe es mal versucht mit dem Mod ordner aber es wird mir nicht im spiel angezeigt.
Also die frage ist wie ich das Addon im LS22 aktiviere

**Comment by s4t4n** [comment]
log datei bitte...
und wo hast du es runtergeladen? - aus den releases oder auf der Codesite als FS22_CVT-Addon-master?

**Comment by Ahirsch57** [comment]
ah hat sich geklärt hab den die Master zip in den modordner getan. Hab es jetzt aber die FS22_CVT_Addon in den Ordner getan funktioniert jetzt aber. Top Addon funktioniert super 👍
