### ISSUE TITLE
LUA error at line 2428

### ISSUE THREAD

**Issue by DrewCZ** [s4t4n/FS22_CVT_Addon#21]
Hi, latest version, unable to play when save loaded, with: 
2023-10-23 03:25 Error: Running LUA method 'update'.
D:/DataTata/FarmMods22/FS22_CVT_Addon/CVT_Addon.lua:2428: attempt to call method 'getDamageAmount' (a nil value)

Whole log in attachment. 
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13065358/log.txt)

**Comment by DrewCZ** [comment]
A new game with a basic set of my mods has the same result. the previous version works on it.

**Comment by s4t4n** [comment]
erm I can't reproduce this error,
on which vehicle did you get that issue?
Because, at this vehicle is no damagesystem available. 
Locomotive or horse?
Btw. the logfile is not complete.

**Comment by DrewCZ** [comment]
well, here is a log when starts from scratch. no horses, no locomotions driven by me. start in easy mode. posting whole complete log.
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13071026/log.txt)

here is another test with new map set for hard level:
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13071229/log.txt)

seems to be like a new incompatibility between the mods

**Comment by s4t4n** [comment]
FS22_easyChangeTransmissionType do an issue btw.

**Comment by DrewCZ** [comment]
removed suspicious mods: 

`FS22_BewareOfStraw.zip
FS22_ClearTrafficJams.zip
FS22_CombineXP.zip
FS22_DustyLandsExtension.zip
FS22_easyChangeTransmissionType.zip
FS22_exhaustExtension.zip
FS22_MM_Impact.zip
FS22_REAcog.zip
FS22_READistantMotorSound.zip
FS22_READynamicDirt.zip
FS22_REAimplements.zip
FS22_REAwheels_1110.zip
FS22_storeDeliveries.zip
FS22_WeightHUD.zip`

new game, map Erlengrat, hard level (no vehicles) result is the same error
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13071345/log.txt)

removed everything except really basic mods: error, log here:
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13071380/log.txt)

**Comment by DrewCZ** [comment]
hope it helps, have no idea which mod causing this error

**Comment by s4t4n** [comment]
Ah, I think I have it now.
please [try 0.3.0.61](https://github.com/s4t4n/FS22_CVT_Addon/releases/tag/v0.3.0.61)
