### ISSUE TITLE
Hydrostat erzeugt schaden

### ISSUE THREAD

**Issue by tomy852** [s4t4n/FS22_CVT_Addon#22]
Hallo, ich habe das Problem wenn ich, z.B. den Telelader mit dem Hydrostatischen Antrieb konfiguriere, fährt er nur noch ca11kmh.
Und der schaden geht auch ziemlich schnell hoch.
Ist ein Fehler oder muss ich was einstellen?
 

[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13196282/log.txt)

**Comment by s4t4n** [comment]
Hi Tomy, der HST wird nochmal überarbeitet.
Ich denke im nächsten update, zuvor kommt noch ein anderer fix.

**Comment by tomy852** [comment]
verstehe, alles klar! Danke für die tolle Arbeit  😊
