### ISSUE TITLE
unable to start engine

### ISSUE THREAD

**Issue by DrewCZ** [s4t4n/FS22_CVT_Addon#24]
Hi, on existing save, or in the new game, I'm unable to start the engine on **any** vehicle. Log attached. 
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13307367/log.txt)

Using version 0.9.9.75, mods are listed on the log file.

**Comment by s4t4n** [comment]
https://github.com/s4t4n/FS22_CVT_Addon/wiki/Features#start-the-motor

**Comment by DrewCZ** [comment]
omg... magic :D
