### ISSUE TITLE
Addon funktioniert nicht im MP

### ISSUE THREAD

**Issue by StefanTreutler1974** [s4t4n/FS22_CVT_Addon#25]
Leider funktioniert dieses Addon nicht  im MP.
Sobald man den Multiplayer startet bricht er ab und lässt sich nicht mehr starten.
Bitte um Korrektur.

**Comment by s4t4n** [comment]
keine Log und keine Fehlerbeschreibung, 
was soll ich da korrigieren ? Kaffee mit Milch?

**Comment by StefanTreutler1974** [comment]
[Gamelog Rechner.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13415681/Gamelog.Rechner.txt)

**Comment by StefanTreutler1974** [comment]
[Gameserverlog.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13415692/Gameserverlog.txt)

**Comment by StefanTreutler1974** [comment]
[Serverlog.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13415701/Serverlog.txt)

**Comment by s4t4n** [comment]
Okay, bereinige mal dein Mod-Verzeichnis, da haben viele mods Errors.

Das aktuelle Problem der Version 74 / 84 vom CVT-Addon tauch hier gar nicht auf.
Dennoch gibt es im Discord bereits den fix dazu, daß mit und ohne CP / AD es wieder funktioniert.
Das Update wird heute/morgen auch im hier im Github erscheinen.

**Comment by StefanTreutler1974** [comment]
Wo finde ich es im Discord ?
