### ISSUE TITLE
Warnings and warnings...

### ISSUE THREAD

**Issue by FirenzeIT** [s4t4n/FS22_CVT_Addon#26]
Hello, with this mod i have many warning, but Less Brake from modhub nothing have anything of this...

Warning: Missing l10n 'input_SETVARIORPM_AXIS' in mod 'FS22_CVT_Addon'
Warning: Missing l10n 'input_SETVARIOCLUTCH_AXIS' in mod 'FS22_CVT_Addon'
2023-11-22 21:26   Warning: Missing l10n 'input_SETVARIORPM_AXIS' in mod 'FS22_CVT_Addon'
2023-11-22 21:26   Warning: Missing l10n 'input_SETVARIOCLUTCH_AXIS' in mod 'FS22_CVT_Addon'

etc... Please fix this or update Less Brake (it's usefull than CVT). thank you.
![1248130_20231122212744_1](https://github.com/s4t4n/FS22_CVT_Addon/assets/113168067/dbd96ebc-ccf2-490c-95af-dfff062cef0c)

**Comment by s4t4n** [comment]
There are simply two translations missing.
Thanks for the info.
Which language in the game have you set?

**Comment by FirenzeIT** [comment]
> There are simply two translations missing. Thanks for the info. Which language in the game have you set?

Ahhh ok, Italian (i'm Italian). 😊
