### ISSUE TITLE
motorTemperature nil

### ISSUE THREAD

**Issue by Jannikhirth** [s4t4n/FS22_CVT_Addon#27]
Bei mir ist die selbe Fehlermeldung auch bei Dashboardlive.
habe aber leider keine Log datei mehr weil das gestern war und ich eben schon ingame war und den post gerade erst gesehen habe

**Comment by s4t4n** [comment]
?

**Comment by Jannikhirth** [comment]
du hast doch bei der neuesten version das problem mit ifkos display das dann die meldung motorTemperature nil kommt in der log und das ist bei mir bei dashboard live auch so

**Comment by s4t4n** [comment]
nur wenn Fahrzeuge mit dem Ifkos dabei aktiv sind.
