### ISSUE TITLE
Hydrostat Handgas

### ISSUE THREAD

**Issue by AlbertLongBong** [s4t4n/FS22_CVT_Addon#28]
Hallo aus irgend einem grund schein das Hydrostat bei mir nicht mit dem handgas vom vca zu interagieren nur wenn ich die die taste um die leistung auf die achse zu schlaten drücke bekomme ich vollgaß auf die achse
Hab zum testen nur den CVT mod, Easy Development tools, VCA, und nachher nochmal mit dem handgas von dem realism gearbox mod probiert nichts funktioniert mfg
https://www.youtube.com/watch?v=8ACT0CscLtE

**Comment by s4t4n** [comment]
danke, schau ich mir an

**Comment by AlbertLongBong** [comment]
Selbe problem immernoch mit der neusten Version. Und jetzt ist das motor starten auch buggy, wenn die kupplung (doppelbelegung) mit auf der zündungstaste habe muss ich die Tatse spammen. Wenn ich die kupplung (doppelbelegung) seperat belege und halte startet er ohne probleme und dann zündung drücke startet er ohne Probleme, alle Einstellungen ausprobiert manuell und manuell mit kupplung überall das selbe

**Comment by s4t4n** [comment]
> wenn die kupplung (doppelbelegung) mit auf der zündungstaste habe
da sag ich jetzt nichts zu^^

Es wird die Motordrehzahl berücksichtigt, nicht das CVTaddon eigene Handgas selbst.
Funktioniert einwandfrei... überprüfe bitte anderweitige Konflikte.

**Comment by AlbertLongBong** [comment]
Genau das hat aber mit der version davor Funktioniert das die Kupplung auf der selben taste wie die Zündung liegt und ich die kupplung nur fürs CVT Addon zum starten habe ansonsten brauche ich sie nicht! Kann ich dir auch gerne zeigen. Habe sonst auch alles gemacht wie in deinen Videos. Und andere Konflikte können dort auch nicht sein habe es mit nur VCA und deinem CVT addon und Vannila Fahrzeug getestet du siehst es ja bei mir im Video. Können uns wenn du willst mal über discord kurzschöießen dann mach ich dir eine Bildschirmübertragung.
