### ISSUE TITLE
Neutraltaste

### ISSUE THREAD

**Issue by micknessi** [s4t4n/FS22_CVT_Addon#30]
Wann gibt es wieder eine Neutraltaste bzw warum gibt es die nicht mehr?

**Comment by s4t4n** [comment]
Die wurde rausgenommen, da es zu viele Probleme damit im Multiplayer gab.
Die Funktion "Parkbremse" in VCA macht im Grunde so gut wie das gleiche, nur daß dort ein "P" und kein"N" steht.
