### ISSUE TITLE
Probleme mit Göweil Ballenwickler

### ISSUE THREAD

**Issue by tomy852** [s4t4n/FS22_CVT_Addon#36]
Hallo, das CVT scheint sich leider nicht so gut mit dem Göweil DLC zu vertragen. 
Sobald ich, z.B. den Göweil Ballenwickler LT-MASTER F115 verwenden will, erscheinen folgende Fehlermeldungen in der Log:
Error: renderOverlay is only allowed in 'draw' callbacks. 

Habs extra nochmal getestet auf Standard Karte nur mit "CVT addon" und "easydev" im Mod Ordner (siehe angehängte Log). 
Das Spiel läuft zwar weiter und man kann noch speichern,, aber bei meinem eigentlichen Spielstand hatte ich  das Problem dass nach der ersten Befüllung keine weiteren mehr angenommen wurden bei dem Gerät.

[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13932928/log.txt)

![fsScreen_2024_01_14_20_50_40](https://github.com/s4t4n/FS22_CVT_Addon/assets/51209411/971cb150-15f2-4e28-a871-a0512ca86e97)

Mfg
tomy852

**Comment by s4t4n** [comment]
Ah okay, ich seh's. Man bedient den wie ein Fahrzeug, aber von Außen.. ohne einsteigen zu können. Da kann das HUD dann nicht kommen, weil kein Tacho HUD da ist, daran orientiert sich das CVTa HUD.

**Comment by tomy852** [comment]
An den Modder wenden... der ist auch gut 😂
Naja, hoffentlich findet sich irgend einen weg das Problem zu umgehen.
Auf jeden Fall Danke für deine Bemühungen 😉

**Comment by Phippsi** [comment]
Hab ebenfalls das selbe Problem mit der Göweilpresse. Mal ne vielleicht blöde Frage, aber ist dieser Error schlimm oder kann man den ignorieren?
