### ISSUE TITLE
CVT Addon speichert den Konfigurationszustand nicht

### ISSUE THREAD

**Issue by LSMT-elMatador** [s4t4n/FS22_CVT_Addon#37]
Hall S4t4n,

als erstes mal Danke für die tolle mod!

Aber leider ist es auf unserem Server so, das bei jedem Neustart des Servers alle Fahrzeuge auf der Map wieder die Konfiguration
CVT Standart haben. 
Auch wenn in den Fahrzeugen kein CVT konfiguriert ist. 
Leider ist das bei einem Server mit 6 Spielern und bis zu 50 Fahrzeugen etwas uncool, wenn man jeden Tag mit allen Fzg´s zur Werkstatt muss um den eigentlichen ist- Zustand wieder herzustellen.
Ebenso ist bei Gemieteten Fahrzeugen zwar das erste konfigurieren möglich, aber bei Neustart des Servers ist das CVT wieder auf Standart und kann nicht mehr zurück konfiguriert werden.
Bei den Schubkarren ist das Problem, das es sich immer wieder als Standart konfiguriert. Auch wenn man es auf "aus" konfiguriert hat.
Leider wollen einige auf dem Server nun ohne CVT Addon spielen. Aber wenn jeder nach jedem Server neustart immer mit allen seinen Fahrzeugen in die Werkstatt muss... naja... lästig und unötig!

Anbei die Server log!

Danke!

[serverLog_Weekend_Farmers.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/13933000/serverLog_Weekend_Farmers.txt)

**Comment by s4t4n** [comment]
Das Problem gab es schon mal und das habe ich gefixt, das kam nach dem update.
Jetzt hab ich es noch mal gege getestet, bei uns speichert er alle Konfigs.
Btw. 50 Fahrzeuge, sind ganz schön viel, dennoch sollte es keine Einschränkung des speichern sein.
Wurde die Version evtl. im bestehenden Savegame aktualisiert?

**Comment by LSMT-elMatador** [comment]
Version wurde von 1.0.0 (mudhub version) auf 1.0.0.01 (Github Version) im bestehenden Server Savegame geändert!
Neues Savegame ist dann aber Schwierig bei (jeder Spieler einzeln zusammengezählt) 500 gesamt Spielstunden.
50 Fahrzeuge = Viel?
6 bespielte höfe. 
Jeder Hof mind. 2 Trecker = 12 - 18 Trecker!
Jeder Hof nen Drescher = 6 Drescher
Jeder Hof mind 1 Schubkarre = 6 Schubkarren
3 Höfe haben je nen Häcksler oder Roder= 3 Häcksler + 3 Roder
Jeder Hof hat nen Frontlader oder Radlader... Manche beides = 6 - 10 Frontlader, Radlader oder Telelader
= 18 Trecker + 6 Drescher + 6 Schubkarren + 3 Häcksler + 3 Roder + 10 Front-, Rad oder Telelader = 46 Fahrzeuge auf einer 4fach map... + Gemeinde mit Pflug und LKW da sind 50 Fzg nicht all zu üppig ausgestattete Höfe...

**Comment by sammygravano** [comment]
Haben das Problem bei uns auch. Jedoch besitzen wir nur 6 Fahrzeuge und es speichert trotzdem keine Getriebe. Das ganze bleibt für ein paar Stunden gespeichert aber danach ist es wieder auf klassisch. Gibt keinen Error oder sonst etwas in den Logs

**Comment by s4t4n** [comment]
sehr merkwürdig, ich kann unseren Server so oft neustarten und sogar die Savegames wechseln.. es bleibt alles gespeichert.

Postet mal bitte die client und server logs

**Comment by sammygravano** [comment]
[log_2024-01-20_22-19-24.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/14002605/log_2024-01-20_22-19-24.txt)
[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/14002611/log.txt)

VehicleInfo Error kann ignoriert werden. War vorher nicht drauf aber hatte trotzdem das Problem

**Comment by LSMT-elMatador** [comment]
Server log hast schon... client log kann man im Moment nicht nachreichen, da auf Grund der "Probleme" die Mod CVT deaktiviert ist. Extra alles umconfigurieren und neu laden ist der Aufwand zu groß.

Trotzdem Danke für Deine Mühe!

**Comment by s4t4n** [comment]
@LSMT-elMatador  
laut deiner Log wird alles ordnungsgemäß gespeicht, alle Einträge sind in de vehicles.xml im svg. vorhanden.
Allerdings gibt es da einen Syncfehler (AD). Ad muß nicht Schuld sein, aber da blieb hier etwas hängen, das kann auch die Verbindung des Root-Servers selbst sein oder irgend ein Script.

`2024-01-14 10:35   Info: [AutoDriveSync] Written 5492163 bits (686520 bytes) in 88 ms
2024-01-14 10:35 connectedToDedicatedServer: true
2024-01-14 10:35 1.000000
2024-01-14 10:35 1.000000
2024-01-14 10:35 1.000000
2024-01-14 10:35 1.000000
2024-01-14 10:35 Error: Running LUA method 'packetReceived'.
dataS/scripts/utils/Utils.lua(461) : attempt to call upvalue 'newFunc' (a nil value)
2024-01-14 10:37   Info: [AD] Info: g_server table: 0x0235b8f43970 g_client table: 0x0235b99647b0 g_dedicatedServer table: 0x0235b9559250 g_dedicatedServerInfo nil getUserProfileAppPath C:/Users/Server/Documents/My Games/FarmingSimulator2022/ getIsClient true getIsServer true isMasterUser true
2024-01-14 10:37   Info: [AD] ADUserDataManager: send user settings ID ###ausgeblendet###= to client`



@sammygravano  !
Zu FS22_VehicleInfo sag ich mal nix, das ding hat schon seit dem 17er oder wann das raus kam nicht wirklich funktioniert. Brauch man das Teil?

Ansonsten hast du einige FS19 Mods in deinem 22er Spiel ! Plus jede Menge nicht identifizierbares. Ich rate dazu, den Modordner mal aufzuräumen.

**Comment by s4t4n** [comment]
dann unterbricht da irgendwas von einem scriptmod das speichern.... beim Server kommt es generell vor, daß er mal nicht korrekt speichert, vor allem wenn der server selbst und gleichzeitig man selbst speichert.
