### ISSUE TITLE
CVT Addon funktioniet im Multiplayer nicht / verhält sich komisch

### ISSUE THREAD

**Issue by PHansen940** [s4t4n/FS22_CVT_Addon#38]
Im Anhang finden sich alle mir zur Verfügung stehenden Logs.

Im Singleplayer funktioniert CVT mit exakt diesen Mods ausgezeichnet.

Zum MP: Ich habe ein SP Spielstand mit der CVT-Version 1.0 aus dem MH erstellt, diesen auf unseren Dedicated Server hochgeladen und dann dort alle Fahrzeuge gekauft. Es hat gar nicht gut funktioniert. Mähdrescher ließen sich gar nicht starten, es kam nicht mal eine Fehlermeldung. Oder ein Warnhinweis a la "Kupplung betätigen zum Motorstart".

Ich habe dann die aktuelle Version aus dem Github geladen und auf dem Server und im Verzeichnis ersetzt. Seit dem lassen sich alle Fahrzeuge zumindest starten. Die Fahrzeuge haben irgendwie alle auch ein CVT (alle verschiedene) verbaut. Wenn ich zum Shop fahre zum konfigurieren, steht der Eintrag immer auf CVT klassisch, egal was ich vorher konfiguriert hatte. Ich kann es im Shop ändern, bestätige und es ändert sich genau nichts. Bedienen lässt sich alles mehr oder weniger gut - d.h. manche Tasten funktionieren gar nicht, manche Tasten tun, was sie sollen.

Welche Fragen kann ich beantworten, um zu helfen?

[log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/14323887/log.txt)
[server_game_log.txt](https://github.com/s4t4n/FS22_CVT_Addon/files/14323892/server_game_log.txt)

**Comment by s4t4n** [comment]
https://github.com/s4t4n/FS22_CVT_Addon/wiki/Videos

**Comment by PHansen940** [comment]
Vielen Dank... ähh... Denke ich. In welchem Video an welcher Stelle wird denn diese Problematik konkret besprochen?

**Comment by s4t4n** [comment]
https://www.youtube.com/watch?v=pxxFl0TlcxY&t=25s
