### ISSUE TITLE
Selecting no CVT Addon config on electric vehicles prevents engine start

### ISSUE THREAD

**Issue by ThePanzafahra** [s4t4n/FS22_CVT_Addon#39]
Steps to reproduce:

1) Buy or rent any electric vehicle (e.g. Jungheinrich ETV 216i)
2) Configure, set "CVT Addon" to "None"
3) Attempt to start motor

See this video for a showcase: [https://youtu.be/M6uvi7CjcDI](url)

**Comment by s4t4n** [comment]
please try it without the vehicle-info script . that script produces weird errors.
