### ISSUE TITLE
Handbrake getting engaged in Modern CVT transmission for both CP and AD while changing the vehicle

### ISSUE THREAD

**Issue by Chipsu92** [s4t4n/FS22_CVT_Addon#49]
Hello, 

First of all great Addon. I really appreciate using it. 

I am struggling to coordinate any AI worker along with your CVT transmission,
I've searched for the info on github and reddit but I couldn't find any answers how to resolve it. 

Let's get to the point - as per the addon description - modern CVT transmission engage the handbrake when leaving the vehicle. 
It turns out this feature doesn't recognize AI and when Course Play or Auto Drive are running and when I exit the vehicle run by AI, Modern CVT act as there is noone in the vehicle and engage the handbrake. Obviously this is causing the vehicle to run under much bigger load and overheats the engine as the bot is still running.

Am I doing something wrong ? Is it some kind of a limitation? I don't believe noone has ever come that issue across before, so either this is new issue or I suck in finding solution on the internet. 
In theory I could swap to CVT classic transmission where there is no such feature as handbrake while leaving the vehicle but I would prefer to keep it as real as possible since I am already using mods enhancing realism. 

Thanks, 

Michal

**Comment by Omnissias** [comment]
I have the same Issue and reported it before. As long as I sit inside of the vehicle it works just fine. When I leave it the Helpers won't operate it anymore cause the Break is engage or only with numbers of 3 KPH and full load.

**Comment by Chipsu92** [comment]
Is there any way to disable the feature which engages handbrake while leaving the vehicle in the code, for modern CVT transmission - this would be great as quick workaround.

**Comment by oldmicha** [comment]
Nabend zusammen. Ich habe das gleiche Problem wie im ersten beschrieben.

**Comment by Chipsu92** [comment]
It seems like patch resolved the issue. Thank you good Sir.
