### ISSUE TITLE
Q: engine/tramsmission not recognized by cvt

### ISSUE THREAD

**Issue by DrewCZ** [s4t4n/FS22_CVT_Addon#52]
Hi, have a question: in mod KS-6B I have no option to set up CVT variant in shop. Motor cfg in the mod is as folows: 
		`<motorConfigurations>

            <motorConfiguration name="SMD-64" hp="150" price="0">

                <motor torqueScale="0.636" minRpm="850" maxRpm="2200" maxForwardSpeed="25" maxBackwardSpeed="15" brakeForce="5" lowBrakeForceScale="0.22" lowBrakeForceSpeedLimit="1">

                    <torque normRpm="0.45" torque="0.9"/>
                    <torque normRpm="0.5" torque="0.97"/>
                    <torque normRpm="0.59" torque="1"/>
                    <torque normRpm="0.72" torque="1"/>
                    <torque normRpm="0.86" torque="0.88"/>
                    <torque normRpm="1" torque="0.72"/>

                </motor>

                <transmission minForwardGearRatio="33.2" maxForwardGearRatio="200" minBackwardGearRatio="55" maxBackwardGearRatio="200" />

            </motorConfiguration>

        </motorConfigurations>`
Plaese help what should I have to add for recognize by your mod and ability for CVT setup? In this case is transmission HST. Thank you.

**Comment by DrewCZ** [comment]
notice: when I try to edit vewhicles.xml in the save, vales are allways reverted to:
`<CVTaddon vOne="1" vTwo="4" vThree="2" CVTCanStart="true" autoDiffs="0" CVTdamage="0.000000" CvtConfigId="1"/>`

**Comment by iSinterra** [comment]
I guess it's because the mod adds a new store category, which cvt addon doesn't recognize. Either you change the store category in the modesc.xml and in the ks_6b.xml, or you add that category to the cvt_addon.lua.

**Comment by DrewCZ** [comment]
@iSinterra thank you. it works well.
